### PR TITLE
update regression tests

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
**Description**
Update regression tests to be consistent with authoritative `develop`

**Type of change**
- [x] New feature (non-breaking change which adds functionality)

**How Has This Been Tested?**
Regression test updated in `gfsda.v16_crtm_regress`.   Build executed and regression tests executed.
  
**Checklist**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Review by emilyhcliu — APPROVED** [review]
Changes look good to me

**Comment by RussTreadon-NOAA** [comment]
Thank you @emilyhcliu for the approval.   This is still a draft.   Another approval will be needed after I change the PR to active status.  I'm waiting for the Orion global ctests to finish before doing so.

**Comment by RussTreadon-NOAA** [comment]
Install `develop:release/gfsda.v16` and `RussTreadon-NOAA:gfsda.v16_crtm_regress` on Orion and WCOSS2 (Cactus).   Run global ctests on both platforms.   

The `global_4dvar` test fails on both machines.   This is consistent with Hera findings.   Since `global_4dvar` works in `develop` and we don't use 4dvar options in GFS v16 time will not be spent investigating the release branch `global_4dvar` failure.

The other global ctests _Pass_ on Orion 
```
Orion-login-1:/work2/noaa/da/rtreadon/git/gsi/gfsda.v16_crtm_regress/build$ ctest -R global
Test project /work2/noaa/da/rtreadon/git/gsi/gfsda.v16_crtm_regress/build
    Start 1: global_3dvar
1/4 Test #1: global_3dvar .....................   Passed  1925.45 sec
    Start 2: global_4dvar
2/4 Test #2: global_4dvar .....................***Failed  540.61 sec
    Start 3: global_4denvar
3/4 Test #3: global_4denvar ...................   Passed  1626.15 sec
    Start 9: global_enkf
4/4 Test #9: global_enkf ......................   Passed  496.44 sec

75% tests passed, 1 tests failed out of 4

Total Test time (real) = 4588.71 sec

The following tests FAILED:
          2 - global_4dvar (Failed)
```


and _Pass_ on WCOSS2
```
russ.treadon@clogin06:/lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/gfsda.v16_crtm_regress/build> ctest -R global
Test project /lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/gfsda.v16_crtm_regress/build
    Start 1: global_3dvar
1/4 Test #1: global_3dvar .....................   Passed  1742.94 sec
    Start 2: global_4dvar
2/4 Test #2: global_4dvar .....................***Failed  420.40 sec
    Start 3: global_4denvar
3/4 Test #3: global_4denvar ...................   Passed  1502.80 sec
    Start 9: global_enkf
4/4 Test #9: global_enkf ......................   Passed  909.61 sec

75% tests passed, 1 tests failed out of 4

Total Test time (real) = 4575.83 sec

The following tests FAILED:
          2 - global_4dvar (Failed)
```


This result is not entirely unexpected.   The primary change in `emilyhcliu:gfsda.v16_crtm` is to `gsi_hera.intel.lua`.   Modulefiles for other machines are not altered.   `emilyhcliu:gfsda.v16_crtm` also changes `gsi_common.lua` by adding `w3nco` to the list of common modules to load.  This module does not alter `gsi.x` or `enkf.x` results.
 
On Hera only the `global_enkf` test passes.   As [explained](https://github.com/NOAA-EMC/GSI/pull/562#issuecomment-1546014590) in PR [#562](https://github.com/NOAA-EMC/GSI/pull/562) this result is expected.   The modified `gsi_heta.intel.lua` pulls in an updated crtm/2.4.0 module containing bug fixes.   `global_3dvar` and `global_4denvar` run the CRTM and hence, update and control analysis results differ.
```
Hera(hfe10):/scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/gfsda.v16_crtm_regress/build$ ctest -R global
Test project /scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/gfsda.v16_crtm_regress/build
    Start 1: global_3dvar
1/4 Test #1: global_3dvar .....................***Failed  1971.54 sec
    Start 2: global_4dvar
2/4 Test #2: global_4dvar .....................***Failed  480.60 sec
    Start 3: global_4denvar
3/4 Test #3: global_4denvar ...................***Failed  1611.59 sec
    Start 9: global_enkf
4/4 Test #9: global_enkf ......................   Passed  832.38 sec

25% tests passed, 3 tests failed out of 4

Total Test time (real) = 4896.20 sec

The following tests FAILED:
          1 - global_3dvar (Failed)
          2 - global_4dvar (Failed)
          3 - global_4denvar (Failed)
```

**Comment by RussTreadon-NOAA** [comment]
@emilyhcliu , your review remains valid even after I changed this PR from draft to active.  Since this is a merge into your branch, I can not squash merge the changes into your branch.   You need to complete the merge.

**Comment by emilyhcliu** [comment]
> @emilyhcliu , your review remains valid even after I changed this PR from draft to active. Since this is a merge into your branch, I can not squash merge the changes into your branch. You need to complete the merge.

@RussTreadon-NOAA I just need to push the green bottom `Merge pull request` to merge your changes to my branch, correct?

**Comment by RussTreadon-NOAA** [comment]
Yes, you should see a green "Merge" or "Squash and Merge" button on the PR.   Click on it.   It may (or may not) allow you to edit a commit log.   If it gives you this option, edit the commit log if you want.   If not, accept what you see and merge the pull request.

**Pull request merged**
